FROM golang:1.15

ARG project_path=/go/src/github.com/BKrajancic/boby

COPY . ${project_path}
WORKDIR ${project_path}

RUN go get -u golang.org/x/lint/golint

WORKDIR ${project_path}/src
CMD ["golint", "-set_exit_status", "./.."]
