FROM golang:1.23

ARG project_path=/src

COPY . ${project_path}
WORKDIR ${project_path}

RUN go get -d -v ./...
RUN go install -v ./...

RUN apt-get -y update
RUN apt-get -y install inkscape

CMD "go" "test" "-v" "./..." "-args" "$config_path"
